### ISSUE TITLE
Cascadia Code Font must be reinstalled after reboot

### ISSUE THREAD

**Issue by dkgreer52** [microsoft/cascadia-code#137]
I've been enjoying the new Cascadia font in Visual Studio 2017 and 2019, but I've discovered that each time I reboot Windows 10 (v1903), I have to reinstall the font to get it to work.  When I reinstall it, Windows says the font is already installed and asks me to confirm the reinstall.  After the reinstall, the font works fine again.

**Comment by DanielKOcean** [comment]
I face the same problem, but the font sometimes disappears even without rebooting. Re-installation and reloading VSCode or VS solves the problem, but WTF?

**Comment by DanielKOcean** [comment]
> I've been enjoying the new Cascadia font in Visual Studio 2017 and 2019, but I've discovered that each time I reboot Windows 10 (v1903), I have to reinstall the font to get it to work. When I reinstall it, Windows says the font is already installed and asks me to confirm the reinstall. After the reinstall, the font works fine again.

Hi, seems that I solved the problem.
1) (Not sure, that this action is needed) In "Properties" -> check "Unblock" checkbox, click "Apply" or "Ok" button, it will remove security mark from a font file;

![Unblock Font File](https://user-images.githubusercontent.com/9781016/68371761-729b1900-0150-11ea-82b4-ce0640713a4f.png)
2) In file drop down menu click "Install for all users" (see attached pic).
![Install Font](https://user-images.githubusercontent.com/9781016/68371441-c5c09c00-014f-11ea-82bb-03ae94dfe581.png)

**Comment by aaronbell** [comment]
Sounds like this issue has been resolved. If you still have troubles, please feel free to re-open!

**Comment by mick-d** [comment]
This is issue is still happening for me with "Cascadia Code PL". The PL version keeps being removed at reboot.

I have the Windows build 19041.329

**Comment by grtrout** [comment]
I had this problem and tried various different things to resolve it. Eventually, I stumbled on a solution that worked. Rather than copying the files to the Fonts directory or using any of the Windows settings dialogues, simply right-clicking on the font files (e.g., *.ttf) and selecting "**Install _for all users_**" did the trick. I've now restarted my computer several times and not seen this issue.

**Comment by mikhey** [comment]
I just submitted a ticket to the IT team at work b/c I thought it was McAfee attempting to "help" me by removing it.  In either case, this is infuriating to say the least!  - Windows 10 1909 Build 18363.1440

I don't have those options in the screenshot shown above.

**Comment by dkgreer52** [comment]
This procedure (steps 1-10) resolved this infuriating issue for me:
https://winaero.com/rebuild-font-cache-windows-10/#:~:text=1%20Press%20Win%20%2B%20R%20shortcut%20keys%20on,the%20contents%20of%20that%20folder.%20More%20items...%20

**Comment by toufa12** [comment]
[DanielKOcean](https://github.com/DanielKOcean) Thank you so much, bro. It works for me.
