### ISSUE TITLE
Feature Request: Remove the ligratures for *) symbol

### ISSUE THREAD

**Issue by vosaica** [microsoft/cascadia-code#443]
# Description of the new feature/enhancement
When using the function pointer in C++ with VSCode, the asterisk will not be in the middle of the brackets. Especially when I am using the bracket colorizer plugin, the right bracket will not be colored to match the left bracket.
![image](https://user-images.githubusercontent.com/57782331/113880646-40cb2d80-97ee-11eb-8c83-a318ed507f2c.png)

This also happens in my CLion, so it was not caused by VSCode

![image](https://user-images.githubusercontent.com/57782331/113882516-ef23a280-97ef-11eb-8cbb-5d295acb3c4e.png)

This problem won't appear when using other fonts that enable the ligatures
Fira Code:

![image](https://user-images.githubusercontent.com/57782331/113881827-5e4cc700-97ef-11eb-80a8-7675f1078942.png)

JetBrains Mono:

![image](https://user-images.githubusercontent.com/57782331/113881932-74f31e00-97ef-11eb-983c-6b4d49d07158.png)

**Comment by DHowett** [comment]
We may instead want to suppress the ligature when it is adjacent to a `(`.

**Comment by vosaica** [comment]
> We may instead want to suppress the ligature when it is adjacent to a `(`.

Sure, I think it will be even better😄

**Comment by abdullahaloo** [comment]
ziz6521999@outlook.com

**Comment by ExE-Boss** [comment]
Or how about a ligature for `(*)`?

**Comment by Nahor** [comment]
> Or how about a ligature for `(*)`?

I assume that would break everything based on bracket matching (e.g. bracket colorizer plugin mentioned in the issue description)

**Comment by msftrncs** [comment]
Note that the problem reported here is actually both directions, `(*` and `*)`, both pretty common in C/C++ code.   It would appear that maybe only the `*)` case was fixed.

**Comment by Badaxis** [comment]
I know this has been closed but the problem is still here with ```*)```. I'm doing pointer casting and the colorization is wrong.
![image](https://github.com/microsoft/cascadia-code/assets/29995442/ab8fc6bc-521d-4834-9b3e-6accf08aa8a4)
